name: Build APK

on:
  push:
    branches:
      - main  # 或者你想要的其他分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # 或其他您需要的发行版

      - name: Grant execute permission
        run: chmod +x ./gradlew

      - name: Run Gradle build
        run: ./gradlew packageRelease --stacktrace
        
      - name: Upload APK
        uses: actions/upload-artifact@v4  # 更新为 v4
        with:
          name: MyApp
          path: app/build/outputs/apk/debug/app-debug.apk
