name: Build APK

on:
  push:
    branches:
      - main  # 或者你想要的其他分支

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # 选择合适的 Java 版本
          distribution: 'adopt'  # 指定 Java 发行版

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew  # 添加此步骤以授予执行权限

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload APK
        uses: actions/upload-artifact@v4  # 更新为 v4
        with:
          name: MyApp
          path: app/build/outputs/apk/debug/app-debug.apk
