name: CI

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Grant execute permission
        run: chmod +x ./gradlew

      - name: Run Gradle build
        run: ./gradlew packageRelease --stacktrace
